name: Build LaTeX document
on:
  schedule:
    # Run every day at 5:00 UTC
    - cron: "0 5 * * *"

  # Not triggered automatically on PR anymore, because we ran out of CI minutes
  # in May and June 2023. So instead just trigger it manually.
  #pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: METIS_DRLD.tex
          latexmk_shell_escape: true
          pre_compile: |
            apk --no-cache add git
            git config --system --add safe.directory /github/workspace
          post_compile: mv METIS_DRLD.pdf "METIS_DRLD.$(date +'%Y%m%dT%H%M%S').${{ github.sha }}.pdf"
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: METIS DRLD
          path: ./*.pdf
          retention-days: 5
