name: Tests

on:
  push:
  pull_request:

  schedule:
    # Run every day at 5:00 UTC
    - cron: "0 5 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  consistency-checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r codes/requirements.github_actions.txt
      - name: Run Pytest
        run: pytest
