# This workflow creates a PR to update the operations wiki export.

name: update_operations

on:
  schedule:
    # Run every 5 minutes past the hour, because the export is created on the hour.
    - cron: "5 * * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Test
        runs: echo "Hello"
